### ISSUE TITLE
Obtener distancia entre 2 puntos

### ISSUE THREAD

**Issue by RodrigoRymd** [gonzalobarrazueta/TF-20181e098-20191a972-201920156#18]
Implementar una función que devuelve la distancia entre 2 coordenadas

**Comment by gonzalobarrazueta** [comment]
Como parámetros ponle `getlongitude(n1, n2)`.
Luego, dentro de la función, descompones cada nodo así: `a, b = n1`

**Comment by gonzalobarrazueta** [comment]
Agrega una validación dónde si los valores de los parámetros de la función tienen la forma: `(10, 15)` y `(15, 10)`, devuelva 0 de frente
